### ISSUE TITLE
Setup a github action to check coding style after each commit/PR

### ISSUE THREAD

**Issue by SuperFola** [SuperFola/DoNotSend#6]

**Comment by siddhantrao23** [comment]
Hey! Would a linter like [https://github.com/marketplace/actions/super-linter](https://github.com/marketplace/actions/super-linter) might be the right thing to use here? I can take this up.

**Comment by SuperFola** [comment]
Hey!

I saw it supports Python3, and known linter such as black and pylint, thus they can be set up to ensure that PEP8 is applied (which is the goal here), so I think it's good!
